# Generated by Django 6.0.1 on 2026-01-15 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usn", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("student_image_blob", models.BinaryField(blank=True, null=True)),
                (
                    "student_image_format",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("face_embedding", models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="attendance.student",
                    ),
                ),
            ],
        ),
    ]
