<<<<<<< HEAD
# Generated by Django 6.0.1 on 2026-01-15 09:25
=======
# Generated by Django 5.0.7 on 2024-07-23 22:32
>>>>>>> dcf51ac (django dir)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usn", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("student_image_blob", models.BinaryField(blank=True, null=True)),
                (
                    "student_image_format",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("face_embedding", models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="attendance.student",
                    ),
                ),
=======
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('studentImage', models.ImageField(upload_to='student_images/')),
                ('face_embedding', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='attendance.student')),
>>>>>>> dcf51ac (django dir)
            ],
        ),
    ]
