# Generated by Django 6.0.1 on 2026-01-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="face_embedding",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="image_blob",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="image_format",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
