# Generated by Django 6.0.1 on 2026-01-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_face_embedding_user_image_blob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("STAFF", "Staff Member"),
                    ("STUDENT", "Student"),
                ],
                default="STAFF",
                max_length=10,
            ),
        ),
    ]
