# Generated by Django 6.0.1 on 2026-01-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="usn",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
